algoritmo "semnome"
// Função : Calculadora
// Autor : Matheus
// Data : 22/09/2025
// Seção de Declarações
 
var
n1, n2 : inteiro

inicio
escreval ("       Progama Calculadora       ")
escreval ("")
escreva ("Digite seu primeiro numero :")
leia (n1)
escreva ("Digite seu segundo numero :")
leia (n2)

escreval (" A soma é :" , n1 + n2)  //ele soma

// Seção de Comandos
fimalgoritmo

