algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações

var
n1, n2: inteiro

inicio
// Seção de Comandos
escreva ("Digite seu primeiro numero: ")
leia (n1)
escreva ("Digite seu segundo numero: ")
leia (n2)

escreval ("  ")

se n1 > n2 entao
   escreval("O número ", n1, " é maior que ",n2)
senao
   escreval("O número ", n2, " é maior que ",n1)
fimse

fimalgoritmo
