algoritmo "exercicio15"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações
 
var
numero: real

inicio
// Seção de Comandos 
escreva("Digite um número: ")
leia(numero)
se numero > 100 entao
   se numero < 200 entao
      escreval("O número está no intervalo entre 100 e 200")
   senao
        escreval("O número não está no intervalo entre 100 e 200")
   fimse
senao
   escreval("O número não está no intervalo entre 100 e 200")
fimse

fimalgoritmo
